### ISSUE TITLE
Control Movement Speed

### ISSUE THREAD

**Issue by fischja** [Poujhit/floating_bubbles#3]
Hi there, would it be possible to add parameters for controlling (1) the speed at which bubbles appear/disappear and (2) the speed at which bubbles move? Great package by the way!

**Comment by Poujhit** [comment]
Okay sure. Will look into it.

**Comment by Poujhit** [comment]
Added the option to control the movement speed of the bubbles using a simple api as of now [https://github.com/Poujhit/floating_bubbles/releases/tag/v2.3.0](https://github.com/Poujhit/floating_bubbles/releases/tag/v2.3.0).
