### ISSUE TITLE
Number of Bubbles less than 10

### ISSUE THREAD

**Issue by LenaWirtz** [Poujhit/floating_bubbles#7]
Why is it not allowed to have less than 10 bubbles?
I only wanted to use 4 large bubbles, and commenting out this part worked without any problems.
`assert(
          noOfBubbles >= 10,
          'Number of Bubbles Cannot be less than 10',
        ),`

**Comment by Poujhit** [comment]
Sure, let me change that.

**Comment by Poujhit** [comment]
Hey @LenaWirtz , it's been fixed. Checkout!

**Comment by LenaWirtz** [comment]
Hey @Poujhit verry cool, sorry for my late reply. Could you also change the FloatingBubbles.alwaysRepeating Number of bubbles? Here the limit is still at 10 :) Thank you
